<?php

if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_5a53e78f125f1',
        'title' => 'RO Pop Up',
        'fields' => array(
            array(
                'key' => 'field_5a53e839640b3',
                'label' => '-DATE RANGE SETTINGS',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_5a53e7c2de886',
                'label' => 'Start Date',
                'name' => 'start_date',
                'type' => 'date_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'm/d/Y',
                'return_format' => 'F j, Y',
                'first_day' => 0,
            ),
            array(
                'key' => 'field_5a53e7f9de887',
                'label' => 'End Date',
                'name' => 'end_date',
                'type' => 'date_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'm/d/Y',
                'return_format' => 'F j, Y',
                'first_day' => 0,
            ),
            array(
                'key' => 'field_5a53e87bce76c',
                'label' => '-CREATION INFO SETTINGS',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_5a5d0c439be04',
                'label' => 'Display Setting',
                'name' => 'display_setting',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '51',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'all_pages' => 'All Pages',
                    'specific_pages' => 'Specific Pages',
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'save_other_choice' => 0,
                'default_value' => '',
                'layout' => 'horizontal',
                'return_format' => 'value',
            ),
            array(
                'key' => 'field_5a53eb31ca60d',
                'label' => 'Display Pages',
                'name' => 'display_pages',
                'type' => 'repeater',
                'instructions' => 'Pop up only appears on the selected pages.',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5a5d0c439be04',
                            'operator' => '==',
                            'value' => 'specific_pages',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => 'Add Page',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5a5d0d139be05',
                        'label' => 'Specified Page',
                        'name' => 'specified_page',
                        'type' => 'post_object',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'post_type' => array(
                        ),
                        'taxonomy' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'return_format' => 'id',
                        'ui' => 1,
                    ),
                ),
            ),
            array(
                'key' => 'field_5a53eb88ca60e',
                'label' => 'Display Pages URL String',
                'name' => 'display_pages_url_string',
                'type' => 'repeater',
                'instructions' => 'Pop up only appears on pages that contain the specified string in their URL.',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5a5d0c439be04',
                            'operator' => '==',
                            'value' => 'specific_pages',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => 'Add URL String',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5a675d9d18487',
                        'label' => 'Specified String',
                        'name' => 'specified_string',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5a5d0d449be06',
                'label' => 'Exclude Pages',
                'name' => 'exclude_pages',
                'type' => 'repeater',
                'instructions' => 'Do not show the pop up on the selected pages.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => 'Add Page',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5a5d0d449be07',
                        'label' => 'Excluded Page',
                        'name' => 'excluded_page',
                        'type' => 'post_object',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'post_type' => array(
                        ),
                        'taxonomy' => array(
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'return_format' => 'id',
                        'ui' => 1,
                    ),
                ),
            ),
            array(
                'key' => 'field_5a6764bc9ced9',
                'label' => 'Exclude Pages URL String',
                'name' => 'exclude_pages_url_string',
                'type' => 'repeater',
                'instructions' => 'Do not show the pop up on pages that contain the specified string in their URL.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => 'Add URL String',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5a6764bc9ceda',
                        'label' => 'Excluded String',
                        'name' => 'excluded_string',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5a53ec72570b3',
                'label' => 'Pop Up Trigger',
                'name' => 'pop_up_trigger',
                'type' => 'radio',
                'instructions' => 'Select the type of pop up.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'delay' => 'Delay -- Pop up appears after a set amount of time',
                    'exit' => 'Exit -- Pop up appears as user attempts to exit site',
                    'scroll' => 'Scroll -- Pop up appears after user scrolls a specified distance on page',
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'save_other_choice' => 0,
                'default_value' => '',
                'layout' => 'vertical',
                'return_format' => 'value',
            ),
            array(
                'key' => 'field_5a53e902ce76e',
                'label' => 'Pop Up Delay',
                'name' => 'pop_up_delay',
                'type' => 'number',
                'instructions' => 'Waits for the specified amount of time before displaying the pop up.',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5a53ec72570b3',
                            'operator' => '==',
                            'value' => 'delay',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '20',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => 'Seconds',
                'min' => '',
                'max' => '',
                'step' => '',
            ),
            array(
                'key' => 'field_5a53e983ce76f',
                'label' => 'Pop Up Delay Type',
                'name' => 'pop_up_delay_type',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5a53ec72570b3',
                            'operator' => '==',
                            'value' => 'delay',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '80',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'page' => 'Page -- Restarts the pop up delay timer if the user navigates to a new page before the pop up has appeared.',
                    'session' => 'Session -- Displays the pop up after the specified time amount of time. Timer does not reset upon page navigation.',
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'save_other_choice' => 0,
                'default_value' => '',
                'layout' => 'vertical',
                'return_format' => 'value',
            ),
            array(
                'key' => 'field_5a53ed8166339',
                'label' => 'Scroll Distance Type',
                'name' => 'scroll_distance_type',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5a53ec72570b3',
                            'operator' => '==',
                            'value' => 'scroll',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'pixels' => 'Pixels',
                    'percentage' => 'Percentage',
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'save_other_choice' => 0,
                'default_value' => '',
                'layout' => 'vertical',
                'return_format' => 'value',
            ),
            array(
                'key' => 'field_5a5cf21244a98',
                'label' => 'Scroll Distance Pixels',
                'name' => 'scroll_distance_pixels',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5a53ec72570b3',
                            'operator' => '==',
                            'value' => 'scroll',
                        ),
                        array(
                            'field' => 'field_5a53ed8166339',
                            'operator' => '==',
                            'value' => 'pixels',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => 'Pixels',
                'min' => '',
                'max' => '',
                'step' => '',
            ),
            array(
                'key' => 'field_5a5cf26544a99',
                'label' => 'Scroll Distance Percentage',
                'name' => 'scroll_distance_percentage',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5a53ec72570b3',
                            'operator' => '==',
                            'value' => 'scroll',
                        ),
                        array(
                            'field' => 'field_5a53ed8166339',
                            'operator' => '==',
                            'value' => 'percentage',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => 'Percentage',
                'min' => '',
                'max' => '',
                'step' => '',
            ),
            array(
                'key' => 'field_5a53ee1228d30',
                'label' => '-POP UP BOX SETTINGS',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_5a53ee6d130f0',
                'label' => 'Page Overlay Color',
                'name' => 'page_overlay_color',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '20',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '#EEEEEE',
            ),
            array(
                'key' => 'field_5a53ee8e130f1',
                'label' => 'Page Overlay Transparency',
                'name' => 'page_overlay_transparency',
                'type' => 'range',
                'instructions' => 'The transparency of the overlay',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '40',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 50,
                'min' => 0,
                'max' => 100,
                'step' => 1,
                'prepend' => 'Transparent',
                'append' => 'Opaque',
            ),
            array(
                'key' => 'field_5a53eeef130f2',
                'label' => 'Background Color',
                'name' => 'background_color',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '20',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
            ),
            array(
                'key' => 'field_5a53ef11130f3',
                'label' => 'Default Text Color',
                'name' => 'default_text_color',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '20',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '#000000',
            ),
            array(
                'key' => 'field_5a53ef5b3ff26',
                'label' => '-BORDER SETTINGS',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_5a53ef953ff28',
                'label' => 'Top Border Text',
                'name' => 'border_text',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '33',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5a53ef763ff27',
                'label' => 'Border Color',
                'name' => 'border_color',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '33',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '#000000',
            ),
            array(
                'key' => 'field_5a53efa73ff29',
                'label' => 'Border Text Color',
                'name' => 'border_text_color',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '33',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
            ),
            array(
                'key' => 'field_5a872386a8a5b',
                'label' => '-STYLE SETTINGS',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_5a8723a2a8a5c',
                'label' => 'Custom CSS',
                'name' => 'custom_css',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_5a8723e0a8a5d',
                'label' => 'Custom CSS (Mobile)',
                'name' => 'custom_css_mobile',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => '',
            ),
            array(
                'key' => 'field_5a53f04126db1',
                'label' => '-MAIN CONTENT SETTINGS',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_5b218fab572c6',
                'label' => 'Content Type',
                'name' => 'pop_up_content_type',
                'type' => 'radio',
                'instructions' => 'Select the type of pop up content.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '100',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'link' => 'Link -- Link to a URL from the popup button',
                    'mailing_list' => 'Mailing List -- Add user email to a mailing list',
                    'comment' => 'Comment -- Leave feedback about the site',
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'save_other_choice' => 0,
                'default_value' => '',
                'layout' => 'vertical',
                'return_format' => 'value',
            ),
            array(
                'key' => 'field_5b43e0af6472a',
                'label' => 'Request User\'s Email Address?',
                'name' => 'request_email',
                'type' => 'radio',
                'instructions' => 'Request user\'s email and provide a checkbox to be added to the site\'s mailing list.<br/>Email is not required to submit the comment.',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5b218fab572c6',
                            'operator' => '==',
                            'value' => 'comment',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'yes' => 'Yes',
                    'no' => 'No',
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'save_other_choice' => 0,
                'default_value' => '',
                'layout' => 'vertical',
                'return_format' => 'value',
            ),
            array(
                'key' => 'field_5b44fdd5b3b1b',
                'label' => 'Notification Email',
                'name' => 'notification_email',
                'type' => 'text',
                'instructions' => 'Email addresses to receive comments submitted by users (separated by commas).<br/>Comments will also be stored as Pop-Up Comments under the Pop-ups menu.',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5b218fab572c6',
                            'operator' => '==',
                            'value' => 'comment',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'ted@example.com, nancy@example.com',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5a53f05926db2',
                'label' => 'Pop Up Image',
                'name' => 'pop_up_image',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5a53f0dc26db3',
                'label' => 'Large Text',
                'name' => 'large_text',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '42',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5a53f11326db4',
                'label' => 'Medium Text',
                'name' => 'medium_text',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '42',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5a53f11c26db5',
                'label' => 'Text Color',
                'name' => 'text_color',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '16',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '#000000',
            ),
            array(
                'key' => 'field_5a53f79b1852b',
                'label' => '-TIME REMAINING SETTINGS',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5b218fab572c6',
                            'operator' => '==',
                            'value' => 'link',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_5a53f5c41852a',
                'label' => 'Time Limit',
                'name' => 'time_limit',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5b218fab572c6',
                            'operator' => '==',
                            'value' => 'link',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => 'Seconds',
                'min' => '',
                'max' => '',
                'step' => '',
            ),
            array(
                'key' => 'field_5a53f7d91852c',
                'label' => 'Time Limit Text Color',
                'name' => 'time_limit_text_color',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5b218fab572c6',
                            'operator' => '==',
                            'value' => 'link',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '#000000',
            ),
            array(
                'key' => 'field_5b2283f888b4e',
                'label' => 'MailChimp Account Information',
                'name' => 'mailchimp_account_information',
                'type' => 'mailchimp',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5b218fab572c6',
                            'operator' => '==',
                            'value' => 'mailing_list',
                        ),
                    ),
                    array(
                        array(
                            'field' => 'field_5b218fab572c6',
                            'operator' => '==',
                            'value' => 'comment',
                        ),
                        array(
                            'field' => 'field_5b43e0af6472a',
                            'operator' => '==',
                            'value' => 'yes',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '100',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array(
                'key' => 'field_5b29360a6b622',
                'label' => 'Thank You Response',
                'name' => 'thank_you_response',
                'type' => 'radio',
                'instructions' => 'Select the type of Thank You response.',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5b218fab572c6',
                            'operator' => '==',
                            'value' => 'mailing_list',
                        ),
                    ),
                    array(
                        array(
                            'field' => 'field_5b218fab572c6',
                            'operator' => '==',
                            'value' => 'comment',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'message' => 'Message -- Display a pop up Thank You message',
                    'page' => 'Page -- Redirect the user to a Thank You page',
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'save_other_choice' => 0,
                'default_value' => '',
                'layout' => 'vertical',
                'return_format' => 'value',
            ),
            array(
                'key' => 'field_5b2936b21d200',
                'label' => 'Thank You Message Large Text',
                'name' => 'message_large_text',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5b218fab572c6',
                            'operator' => '==',
                            'value' => 'mailing_list',
                        ),
                        array(
                            'field' => 'field_5b29360a6b622',
                            'operator' => '==',
                            'value' => 'message',
                        ),
                    ),
                    array(
                        array(
                            'field' => 'field_5b218fab572c6',
                            'operator' => '==',
                            'value' => 'comment',
                        ),
                        array(
                            'field' => 'field_5b29360a6b622',
                            'operator' => '==',
                            'value' => 'message',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5b2936eb1d201',
                'label' => 'Thank You Message Medium Text',
                'name' => 'message_medium_text',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5b218fab572c6',
                            'operator' => '==',
                            'value' => 'mailing_list',
                        ),
                        array(
                            'field' => 'field_5b29360a6b622',
                            'operator' => '==',
                            'value' => 'message',
                        ),
                    ),
                    array(
                        array(
                            'field' => 'field_5b218fab572c6',
                            'operator' => '==',
                            'value' => 'comment',
                        ),
                        array(
                            'field' => 'field_5b29360a6b622',
                            'operator' => '==',
                            'value' => 'message',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5b2937324e335',
                'label' => 'Thank You Page',
                'name' => 'thank_you_page',
                'type' => 'page_link',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5b218fab572c6',
                            'operator' => '==',
                            'value' => 'mailing_list',
                        ),
                        array(
                            'field' => 'field_5b29360a6b622',
                            'operator' => '==',
                            'value' => 'page',
                        ),
                    ),
                    array(
                        array(
                            'field' => 'field_5b218fab572c6',
                            'operator' => '==',
                            'value' => 'comment',
                        ),
                        array(
                            'field' => 'field_5b29360a6b622',
                            'operator' => '==',
                            'value' => 'page',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array(
                ),
                'taxonomy' => array(
                ),
                'allow_null' => 0,
                'allow_archives' => 1,
                'multiple' => 0,
            ),
            array(
                'key' => 'field_5a53f8131852d',
                'label' => '-CTA BUTTON SETTINGS',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_5a53f81f1852e',
                'label' => 'Button Text',
                'name' => 'button_text',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '35',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5a53f8361852f',
                'label' => 'Button Link',
                'name' => 'button_link',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5b218fab572c6',
                            'operator' => '==',
                            'value' => 'link',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '35',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'http://www.example.com',
            ),
            array(
                'key' => 'field_5a53f85518530',
                'label' => 'Button Color',
                'name' => 'button_color',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '15',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '#0000FF',
            ),
            array(
                'key' => 'field_5a53f87718531',
                'label' => 'Button Text Color',
                'name' => 'button_text_color',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '15',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '#000000',
            ),
            array(
                'key' => 'field_5a53f9009958d',
                'label' => '-DISMISS SETTINGS',
                'name' => '',
                'type' => 'message',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'new_lines' => 'wpautop',
                'esc_html' => 0,
            ),
            array(
                'key' => 'field_5a53f8d89958b',
                'label' => 'Dismiss Text',
                'name' => 'dismiss_text',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5a53f8eb9958c',
                'label' => 'Dismiss Text Color',
                'name' => 'dismiss_text_color',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '#000000',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'pop-up',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));
    
    endif;